#!/bin/bash
# Export LLaMA Factory Fine-tuned Models to Ollama
# Converts checkpoints to Ollama-compatible format

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

show_banner() {
    echo ""
    echo "========================================="
    echo "  Model Export to Ollama"
    echo "  Agent 3: Development Environments"
    echo "========================================="
    echo ""
}

# Check if Ollama is running
check_ollama() {
    log_info "Checking Ollama service..."

    if ! curl -s http://localhost:11434/api/tags > /dev/null; then
        log_error "Ollama is not running on localhost:11434"
        log_info "Start Ollama with: ollama serve"
        return 1
    fi

    log_success "Ollama is running"
    return 0
}

# Merge LoRA weights with base model
merge_lora_weights() {
    local checkpoint_dir="$1"
    local output_dir="$2"

    log_info "Merging LoRA weights with base model..."

    # Check if checkpoint exists
    if [ ! -d "$checkpoint_dir" ]; then
        log_error "Checkpoint directory not found: $checkpoint_dir"
        return 1
    fi

    # Use LLaMA Factory's merge script
    docker exec agent3-llama-factory llamafactory-cli export \
        --model_name_or_path "$checkpoint_dir" \
        --adapter_name_or_path "$checkpoint_dir" \
        --template default \
        --finetuning_type lora \
        --export_dir "$output_dir" \
        --export_size 2 \
        --export_device cpu \
        --export_legacy_format False

    log_success "LoRA weights merged successfully"
}

# Create Ollama Modelfile
create_modelfile() {
    local model_path="$1"
    local model_name="$2"
    local modelfile_path="$3"

    log_info "Creating Ollama Modelfile..."

    cat > "$modelfile_path" <<EOF
# Modelfile for ${model_name}
# Generated by Agent 3 Fine-tuning Pipeline

FROM ${model_path}

# Template
TEMPLATE """{{ if .System }}<|im_start|>system
{{ .System }}<|im_end|>
{{ end }}{{ if .Prompt }}<|im_start|>user
{{ .Prompt }}<|im_end|>
{{ end }}<|im_start|>assistant
"""

# Parameters
PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER top_k 40
PARAMETER repeat_penalty 1.1
PARAMETER stop "<|im_start|>"
PARAMETER stop "<|im_end|>"

# System message
SYSTEM """You are a helpful AI assistant trained for specific tasks. Provide clear, accurate, and concise responses."""
EOF

    log_success "Modelfile created at: $modelfile_path"
}

# Import model to Ollama
import_to_ollama() {
    local modelfile_path="$1"
    local model_name="$2"

    log_info "Importing model to Ollama as '$model_name'..."

    # Create model in Ollama
    if ollama create "$model_name" -f "$modelfile_path"; then
        log_success "Model '$model_name' imported to Ollama"
        return 0
    else
        log_error "Failed to import model to Ollama"
        return 1
    fi
}

# Test the imported model
test_model() {
    local model_name="$1"

    log_info "Testing model '$model_name'..."

    local test_prompt="Hello! Can you introduce yourself?"

    log_info "Sending test prompt: $test_prompt"

    local response=$(ollama run "$model_name" "$test_prompt" --verbose=false 2>&1)

    echo ""
    echo "Model Response:"
    echo "───────────────────────────────────────"
    echo "$response"
    echo "───────────────────────────────────────"
    echo ""

    if [ -n "$response" ]; then
        log_success "Model test successful!"
        return 0
    else
        log_warning "Model test produced no output"
        return 1
    fi
}

# List Ollama models
list_models() {
    log_info "Available Ollama models:"
    echo ""
    ollama list
    echo ""
}

# Main export function
export_model() {
    local checkpoint_path="$1"
    local model_name="$2"
    local skip_merge="${3:-false}"

    show_banner

    # Validate inputs
    if [ -z "$checkpoint_path" ] || [ -z "$model_name" ]; then
        log_error "Usage: $0 <checkpoint_path> <model_name> [skip_merge]"
        log_info "Example: $0 /app/output/student-chat-model/checkpoint-final my-chat-model"
        exit 1
    fi

    # Check Ollama
    if ! check_ollama; then
        exit 1
    fi

    # Determine if checkpoint is in container or host
    if [[ "$checkpoint_path" == /app/* ]]; then
        # Path is inside container
        local container_path="$checkpoint_path"
        local host_path="${checkpoint_path/\/app\/output/$(pwd)/../checkpoints}"
    else
        # Path is on host
        local host_path="$checkpoint_path"
        local container_path="/app/output/$(basename $checkpoint_path)"
    fi

    log_info "Checkpoint path: $checkpoint_path"
    log_info "Model name: $model_name"

    # Create temporary directory for export
    local export_dir="/tmp/ollama-export-$$"
    mkdir -p "$export_dir"

    # Step 1: Merge LoRA weights (if not skipped)
    if [ "$skip_merge" != "true" ]; then
        local merged_dir="$export_dir/merged"
        merge_lora_weights "$container_path" "$merged_dir"
        local model_path="$merged_dir"
    else
        log_info "Skipping LoRA merge (using checkpoint directly)"
        local model_path="$host_path"
    fi

    # Step 2: Create Modelfile
    local modelfile="$export_dir/Modelfile"
    create_modelfile "$model_path" "$model_name" "$modelfile"

    # Step 3: Import to Ollama
    if import_to_ollama "$modelfile" "$model_name"; then
        # Step 4: Test model
        test_model "$model_name"

        # Cleanup
        log_info "Cleaning up temporary files..."
        rm -rf "$export_dir"

        log_success "Export complete!"
        echo ""
        log_info "You can now use your model with:"
        echo "  ollama run $model_name"
        echo ""
        log_info "Or via API:"
        echo "  curl http://localhost:11434/api/generate -d '{\"model\":\"$model_name\",\"prompt\":\"Hello\"}'"
        echo ""

        return 0
    else
        # Cleanup
        rm -rf "$export_dir"
        log_error "Export failed"
        return 1
    fi
}

# Show help
show_help() {
    cat << EOF
Usage: $0 <checkpoint_path> <model_name> [options]

Arguments:
    checkpoint_path     Path to fine-tuned model checkpoint
                       (e.g., /app/output/student-chat-model/checkpoint-final)

    model_name         Name for the model in Ollama
                       (e.g., my-chat-model)

Options:
    --skip-merge       Skip LoRA weight merging (use for full fine-tuned models)
    --test-only        Only test an existing Ollama model
    --list             List all Ollama models

Examples:
    # Export fine-tuned model
    $0 /app/output/student-chat-model/checkpoint-final student-chat

    # Export from host path
    $0 ./checkpoints/my-model/checkpoint-final my-model

    # Skip merge for full fine-tuned models
    $0 /app/output/full-model/checkpoint-final full-model --skip-merge

    # Test existing model
    $0 --test-only student-chat

    # List models
    $0 --list

Requirements:
    - Ollama installed and running (ollama serve)
    - LLaMA Factory container running (for LoRA merge)
    - Fine-tuned model checkpoint

Notes:
    - LoRA adapters will be merged with base model automatically
    - Merged model will be imported to Ollama
    - You can customize the Modelfile after export

EOF
}

# Parse arguments
main() {
    case "${1:-}" in
        --list)
            list_models
            ;;
        --test-only)
            if [ -z "$2" ]; then
                log_error "Model name required for --test-only"
                exit 1
            fi
            test_model "$2"
            ;;
        --help|-h|help)
            show_help
            ;;
        *)
            if [ $# -lt 2 ]; then
                show_help
                exit 1
            fi

            local skip_merge="false"
            if [ "$3" = "--skip-merge" ]; then
                skip_merge="true"
            fi

            export_model "$1" "$2" "$skip_merge"
            ;;
    esac
}

main "$@"
